; Configuration Files


; Basic Config
[BASIC]
# Put your IP adress. Dont use brackets "" !!!!!!!!!!
# if you want use Draconus on vps, put: vps
# if you put ""  - Two brackets. Default IP (127.0.0.1) will be set.
IP = 192.168.100.21

# format code uses beetwen clients and servers
FORMAT_CODE = utf-8

# dont show no important messagess (yes = less flood, but less info)
# Log files still log everything
MSG_NO_IMPORTANT = no

# pause (in seconds) between Worm connection attempts
# small value generates a lot of traffic, but for testing it is good
WORM_PAUSE_CONN = 3

# Place where Draconus make dirs like output, sockets, payload etc.
# 'main' means root directory of Draconus application
MAIN_DIR = main

# Enable Http server. 
HTTP_ENABLE = yes

# work only on Draconus. Additionally uses the standard print function.
MSG_VANILA_PRINT = no

# additional log file in JSON mode
MSG_JSON = yes

# every server was created will be saved
AUTO_SAVE_SERVER = no


[HEADERS]
MSG_SYS_HEADERS = "###@@@@"

[DIRS]
SOCKET_DIR = _sockets
OUTPUT_DIR = OUTPUT
EXTRAS_DIR = EXTRAS


[ADVANCED]
MICRO_SERVER_LIMIT = 30
HTTP_ADMIN_ENABLE = yes
RAW_LEN = 2048
UNIX_RAW_LEN = 2048
UNIX_SOCKET_FORMAT = utf-8
ACCEPT_CONN_TIMEOUT = 3
PROC_CYCLE_PAUSE = 2

;Pause beetwen read from server pipe
PAUSE_OVERFLOW = 0.2



[DEV]
MSG_DEV = no
LOAD_ALL_SERVERS = no
